defaultEntryPoints = ["http","https"]
logLevel = "DEBUG"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
    [[entryPoints.https.tls.certificates]]
    certFile = "/cloudhost.hsrw.eu.cert"
    keyFile = "/cloudhost.hsrw.eu.key"
  [[entryPoints.https.tls.certificates]]
    certFile = "/git.hsrw.eu.cert"
    keyFile = "/git.hsrw.eu.key"


[docker]
# domain = "docker.localhost"
exposedByDefault = false
